# Plotly Walkthrough

Plotly is an open source graphing library for Python. This module shows basic visualizations that can be done using Plotly. 

>_Built on top of the Plotly JavaScript library (plotly.js), plotly enables Python users to create beautiful interactive web-based visualizations that can be displayed in Jupyter notebooks, saved to standalone HTML files, or served as part of pure Python-built web applications using Dash. The plotly Python library is sometimes referred to as "plotly.py" to differentiate it from the JavaScript library._

In [1]:
import plotly.express as px # plotly library
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

Plotly offers a variety of [visualizations](https://plotly.com/python/). From basic graphs to advanced interactive visualizations. We will go through different type of visualizations plotly is capable of.

## Bar graph

With px.bar, each row of the DataFrame is represented as a rectangular mark. Customization documentation can be found [here](https://plotly.com/python/styling-plotly-express/). 

Every visualization created with plotly offers interactivy right away. If you hover over the bars a tooltip with information appears. Also, on the top right corner there are multiple option to zoom, pan, select, and more! You can even download a png version of the visualization. Try it yourself!

In [2]:
px.bar(y=[1, 1, 2, 3, 5, 8, 13, 21], title = "Example Bar graph", labels = {"x":"X axis", "y":"Y axis"})

You can also create a figure object to have more flexibility later on.

In [3]:
fig = px.bar(y=[1, 1, 2, 3, 5, 8, 13, 21], title = "Example Bar graph", labels = {"x":"X axis", "y":"Y axis"})
fig.show()

## Scatter Plot

With px.scatter, each data point is represented as a marker point, whose location is given by the x and y columns. Here we are using the [Iris Dataset](https://archive.ics.uci.edu/ml/datasets/iris) to plot sepal width vs length.

In [4]:
df = px.data.iris()
fig = px.scatter(df, 
                 x="sepal_width", 
                 y="sepal_length", 
                 color="species",
                 size='petal_length', 
                 hover_data=['petal_width'], # We can add more data to the tooltip
                 labels={"sepal_length": "Sepal length", 
                         "sepal_width": "Sepal width",
                         "species": "Species"}, 
                 title ="Sepal width vs Sepal length")
fig.show()

## Line graphs

With px.line, each data point is represented as a vertex (which location is given by the x and y columns) of a polyline mark in 2D space. Here we are showing the life expectancy of every country in America.

In [5]:
df = px.data.gapminder().query("continent=='Americas'")
fig = px.line(df, x="year", y="lifeExp", color='country', title="Life expectancy in America countries")
fig.show()

## Histograms

In plotly, a histogram is an aggregated bar chart, with several possible aggregation functions (e.g. sum, average, count...). Also, the data to be binned can be numerical data but also categorical or date data. By default, the number of bins is chosen so that this number is comparable to the typical number of samples in a bin. This number can be customized, as well as the range of values.

In [6]:
x = np.random.randn(500)
fig = px.histogram(x=x, histnorm='probability')

fig.show()

## 3D surface Plot

There are a wide variety of visualizations possible with plotly. We will be using mostly plotly express. `plotly.graph_objects`contains more complex visualizations such as this cool 3D surface plot of Mt. Bruno. You can interact with it to see it from all angles.

In [7]:
import plotly.graph_objects as go

z_data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv')

fig = go.Figure(data=[go.Surface(z=z_data.values)])

fig.update_layout(title='Mt Bruno Elevation', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()

---
## ▶ START DEMO HERE — UFO Sightings

> **Instructor:** Begin the in-class demo at this cell. The cells above (Plotly intro with toy data) are reference only — skip them during the 6:20–7:00 demo block.

> **Dataset:** `clean_ufo_data.csv` (already in this folder)

> **Demo sequence:** bar chart (WA state) → scatter → cumulative line (top 5 states) → choropleth → animated choropleth

> **Bird strikes exercises** (cells below the choropleth section): good fallback activity for students who finish early or don't have their MP1 data loaded yet.

# UFO Sightings dataset

Let's create some visualizations using plotly with a dataset of [UFO sigthings](https://www.kaggle.com/thaddeussegura/ufo-sightings) in the US.

In [8]:
df = pd.read_csv("clean_ufo_data.csv")
df.tail()

,id,occurred_date_time,city,state,shape,duration,summary,details_url,posted_date
120780,13010,09?/?/1975,Oscoda,MI,Unknown,2-3 min,Funny flashing lights that hovered then just d...,http://www.nuforc.org/webreports/013/S13010.html,6/6/00
120781,98603,NaN,Kelowna (Canada),BC,NaN,NaN,"They were close to my home, hope they come soo...",http://www.nuforc.org/webreports/098/S98603.html,7/3/13
120782,86594,NaN,Subotica,NaN,NaN,NaN,Objects was moving very fast on this about pos...,http://www.nuforc.org/webreports/086/S86594.html,8/5/12
120783,21758,??/??/??,Trevorton,PA,Unknown,Long Ago,Fast UFO flyies across mountain areas. Telsa ...,http://www.nuforc.org/webreports/021/S21758.html,2/22/02
120784,107717,2010,Amherst,VA,NaN,NaN,This is a still shot recently taken from video...,http://www.nuforc.org/webreports/107/S107717.html,3/18/14

The dates seem to have different formats. Let's change them all to datetime and put any unrecognized format as "Not a Time" (NaT) using the `errors='coerce'` option. This can take some time to finish.

In [9]:
df["occurred_date_time"] = pd.to_datetime(df["occurred_date_time"], errors='coerce')

In [10]:
df.tail()

,id,occurred_date_time,city,state,shape,duration,summary,details_url,posted_date
120780,13010,NaT,Oscoda,MI,Unknown,2-3 min,Funny flashing lights that hovered then just d...,http://www.nuforc.org/webreports/013/S13010.html,6/6/00
120781,98603,NaT,Kelowna (Canada),BC,NaN,NaN,"They were close to my home, hope they come soo...",http://www.nuforc.org/webreports/098/S98603.html,7/3/13
120782,86594,NaT,Subotica,NaN,NaN,NaN,Objects was moving very fast on this about pos...,http://www.nuforc.org/webreports/086/S86594.html,8/5/12
120783,21758,NaT,Trevorton,PA,Unknown,Long Ago,Fast UFO flyies across mountain areas. Telsa ...,http://www.nuforc.org/webreports/021/S21758.html,2/22/02
120784,107717,2010-01-01,Amherst,VA,NaN,NaN,This is a still shot recently taken from video...,http://www.nuforc.org/webreports/107/S107717.html,3/18/14

They seem to have datetime format now, but a lot of them are NaT. We will drop any rows where date time is NaT.

In [11]:
df = df.dropna(subset=['occurred_date_time'])
df.tail()

,id,occurred_date_time,city,state,shape,duration,summary,details_url,posted_date
120705,11929,2022-07-14 00:30:00,"Albury (NSW, Australia)",NaN,Triangle,25 minutes,Observed 3 white lights lines up like traffic ...,http://www.nuforc.org/webreports/011/S11929.html,2/16/00
120706,14263,1984-07-01 00:30:00,Kentville (Canada),NS,Light,NaN,Hello my name is Donnie Duffy. i was camping ...,http://www.nuforc.org/webreports/014/S14263.html,12/2/00
120707,147505,2022-07-14 00:00:00,Reidsville,NC,Cigar,5 months,There's normally one really bright one and the...,http://www.nuforc.org/webreports/147/S147505.html,7/12/19
120708,98648,2022-07-14 00:00:00,New York City,NY,Circle,20 seconds I think I lost,(HOAX??)) All I remember is I am looking out ...,http://www.nuforc.org/webreports/098/S98648.html,7/3/13
120784,107717,2010-01-01 00:00:00,Amherst,VA,NaN,NaN,This is a still shot recently taken from video...,http://www.nuforc.org/webreports/107/S107717.html,3/18/14

Now it looks much better!

Let's group the data by year and state. Using `groupby` we can count how many ocurrences there are for any combination of year an state.

In [12]:
df_grouped = df.groupby([df["occurred_date_time"].dt.year, df["state"]])["id"].count().reset_index(name="sightings")
df_grouped.rename(columns={'occurred_date_time':'year'}, inplace=True) # we will rename this column to be more representative (this is not necessary)
df_grouped.head()

   year state  sightings
0  1921    GA          1
1  1925    IL          1
2  1929    OR          1
3  1929    PA          1
4  1930    AB          1

Now we have a dataframe including year, state and number of sightings. Let's take a look into the data for Washington state.

In [13]:
df_wa = df_grouped[df_grouped["state"]=="WA"]
df_wa.tail(5)

      year state  sightings
3433  2018    WA        162
3494  2019    WA         87
3531  2022    WA          2
3580  2070    WA          3
3621  2071    WA          9

Let's create a bar chart of the sightings per year for Washington state

In [14]:
fig = px.bar(df_wa,x="year",y="sightings", title="UFO sightings in Washington state")
fig.show()

Creating a scatter plot of the same data is easy!

In [15]:
fig = px.scatter(df_wa, x="year", y="sightings", title="UFO sightings in Washington state")
fig.show()

We want to see this data for all of the states at the same time. Let's create a scatter plot that includes all of the states.

In [16]:
fig = px.scatter(df_grouped, x="year", y="sightings", color="state", title="UFO sightings in USA per state")
fig.show()

We can also create a new column that includes the cumulative sum of all the sightings.

In [17]:
df_grouped['total'] = df_grouped.groupby(['state'])['sightings'].apply(lambda x: x.cumsum())
df_grouped.tail()

      year state  sightings  total
3619  2071    TX          8   4999
3620  2071    VA          1   2188
3621  2071    WA          9   5947
3622  2071    WI          2   2017
3623  2071    WV          4    742

Using this data we can plot total UFO sightings per state using a line graph. You can filter data in the visualization using the state key.

In [18]:
fig = px.line(df_grouped, x="year", y="total", color='state', title = "Total UFO Sightings per state")
fig.show()

There's too much occlusion. Let's do the same visualization but with the top 5 states with most sightings.

In [19]:
top5 = df_grouped.groupby("state")["sightings"].sum().sort_values(ascending=False).head(5).reset_index()["state"]
top5

0    CA
1    FL
2    WA
3    TX
4    NY
Name: state, dtype: object

In [20]:
fig = px.line(df_grouped[df_grouped["state"].isin(top5)], 
              x="year", 
              y="total", 
              color='state', 
              title = "Top 5 states with most UFO sightings")
fig.show()

There is still some occlusion. If we have the data per state maybe using a map is better to show all the information at the same time.

## Choropleth map

Using plotly we will create a choropleth map that show sightings per state. Let's show all the sightings in the year 2005. We will be using a color scale. You can read more about plotly built-in color scales [here](https://plotly.com/python/builtin-colorscales/).

In [21]:
year_df = df_grouped[df_grouped["year"] == 2005]

fig = px.choropleth(year_df, 
                    locations = "state",  
                    locationmode="USA-states", 
                    color='sightings',      
                    color_continuous_scale="bluyl",
                    labels={'sightings':'UFO Sightings', "state":"State"},
                    scope="usa")

fig.update_layout(title= "UFO Sightings in 2005", 
                  margin={"r":20,"t":100,"l":20,"b":20})

fig.show()

Let's also show the year. We can do that by adding a slider using the `animation_frame` option.

In [22]:
fig = px.choropleth(df_grouped, 
                    locations=df_grouped['state'],  
                    locationmode="USA-states", 
                    color='sightings',      
                    color_continuous_scale="bluyl",
                    scope="usa",
                    animation_frame="year", 
                    title= "UFO Sightings per year",
                    labels={'sightings':'UFO Sightings', "state":"State"})
fig.show()

Now we can move through the years! You can see that the range of UFO sightings changes for each year. Comparing between years is more difficult that way. To fix this we can add a fixed range for all of the years with the option `range_color`.

In [23]:
fig = px.choropleth(df_grouped, 
                    locations=df_grouped['state'],  
                    locationmode="USA-states", 
                    color='sightings',      
                    color_continuous_scale="bluyl",
                    range_color=(0, df_grouped["sightings"].max()), # Fixed color range
                    scope="usa",
                    animation_frame="year", 
                    title= "UFO Sightings per year",
                    labels={'sightings':'UFO Sightings', "state":"State"})
fig.update_layout(margin={"r":20,"t":100,"l":20,"b":20})
fig.show()

Now we have an interactive visualization that shows all the sightings per year and state at the same time.

# Exercises

Refer to the examples above to guide you in completing the following exercises. You may need to do some research in the Plotly or Pandas documentation to help you out.

For this set of exercises you will be using the [Bird Strikes](https://www.kaggle.com/breana/bird-strikes) dataset. The dataset contains a record of each reported wildlife strike of a military, commercial, or civil aircraft between 1990 and 2015. Each row contains the incident date, aircraft operator, aircraft make and model, airport name and location, species name and quantity, and aircraft damage.

In [24]:
bird_df = pd.read_csv("bird_strikes.csv")

In [25]:
bird_df.head()

,Record ID,Incident Year,Incident Month,Incident Day,Operator ID,Operator,Aircraft,Aircraft Type,Airport ID,Airport,...,Height,Speed,Distance,Species ID,Species Name,Species Quantity,Flight Impact,Fatalities,Injuries,Aircraft Damage
0,127128,1990,1,1,DAL,DELTA AIR LINES,B-757-200,A,KCVG,CINCINNATI/NORTHERN KENTUCKY INTL ARPT,...,NaN,NaN,NaN,NE1,GULL,1,NaN,NaN,NaN,1
1,129779,1990,1,1,HAL,HAWAIIAN AIR,DC-9,A,PHLI,LIHUE ARPT,...,0.0,NaN,0.0,ZZ201,HOUSE SPARROW,1,NaN,NaN,NaN,0
2,129780,1990,1,2,UNK,UNKNOWN,UNKNOWN,NaN,PHLI,LIHUE ARPT,...,NaN,NaN,0.0,R1101,BARN OWL,1,NaN,NaN,NaN,0
3,2258,1990,1,3,MIL,MILITARY,A-10A,A,KMYR,MYRTLE BEACH INTL,...,200.0,138.0,NaN,UNKBM,UNKNOWN MEDIUM BIRD,1,NaN,NaN,NaN,0
4,2257,1990,1,3,MIL,MILITARY,F-16,A,KJAX,JACKSONVILLE INTL,...,100.0,200.0,NaN,ZX,FINCH,1,NaN,NaN,NaN,0

## Exercise 1

1. Plot a bar graph of incidents per year.
2. Plot a bar graph of incidents per year for Air Canada, Delta Air Lines, American Airlines and Hawaiian Airlines in the same visualization.

In [26]:
# 1.1 Graph bar of incidents per year
year_df = bird_df.groupby(['Incident Year'])["Record ID"].count().reset_index(name="Incidents")
year_df.head()

   Incident Year  Incidents
0           1990       2099
1           1991       2672
2           1992       2816
3           1993       2849
4           1994       2938

In [27]:
fig = px.bar(year_df, x = "Incident Year", y = "Incidents")
fig.update_layout(title = "Bird incidents per year")
fig.show()

In [28]:
# 1.2 Bar graph of incidents per airline
filtered_df = bird_df[(bird_df["Operator"] == "AIR CANADA") | 
                      (bird_df["Operator"] == "DELTA AIR LINES") | 
                      (bird_df["Operator"] == "AMERICAN AIRLINES") |
                      (bird_df["Operator"] == "HAWAIIAN AIR")]
filtered_df.head()

,Record ID,Incident Year,Incident Month,Incident Day,Operator ID,Operator,Aircraft,Aircraft Type,Airport ID,Airport,...,Height,Speed,Distance,Species ID,Species Name,Species Quantity,Flight Impact,Fatalities,Injuries,Aircraft Damage
0,127128,1990,1,1,DAL,DELTA AIR LINES,B-757-200,A,KCVG,CINCINNATI/NORTHERN KENTUCKY INTL ARPT,...,NaN,NaN,NaN,NE1,GULL,1,NaN,NaN,NaN,1
1,129779,1990,1,1,HAL,HAWAIIAN AIR,DC-9,A,PHLI,LIHUE ARPT,...,0.0,NaN,0.0,ZZ201,HOUSE SPARROW,1,NaN,NaN,NaN,0
5,129734,1990,1,4,HAL,HAWAIIAN AIR,DC-9,A,PHLI,LIHUE ARPT,...,0.0,NaN,0.0,ZY1,MUNIAS,1,NaN,NaN,NaN,0
15,129739,1990,1,12,HAL,HAWAIIAN AIR,DC-9,A,PHLI,LIHUE ARPT,...,0.0,NaN,0.0,ZY1,MUNIAS,1,NaN,NaN,NaN,0
47,120677,1990,2,11,AAL,AMERICAN AIRLINES,B-767-200,A,ZZZZ,UNKNOWN,...,NaN,NaN,NaN,UNKBM,UNKNOWN MEDIUM BIRD,1,NaN,NaN,NaN,1

In [29]:
operator_df = filtered_df.groupby(['Incident Year', "Operator"])["Record ID"].count().reset_index(name="Incidents")
operator_df.head()

   Incident Year           Operator  Incidents
0           1990         AIR CANADA          2
1           1990  AMERICAN AIRLINES        453
2           1990    DELTA AIR LINES         52
3           1990       HAWAIIAN AIR         15
4           1991         AIR CANADA          7

In [30]:
fig = px.bar(operator_df, x = "Incident Year", y = "Incidents", color = "Operator", barmode='group')
fig.update_layout(title = "Bird incidents per year and operator")
fig.show()

## Exercise 2
 
1. Make a scatter plot of the top 10 airlines with most incidents
2. Plot a line graph of cumulative incidents per year for Air Canada, Delta, American Airlines and Hawaiian Airlines in the same visualization.

In [31]:
# 2.1
bird_grouped = bird_df.groupby(['Incident Year', "Operator"])["Record ID"].count().reset_index(name="Incidents")

In [32]:
top10 = bird_grouped.groupby("Operator")["Incidents"].sum().sort_values(ascending=False).head(10).reset_index()["Operator"]
top10

0               UNKNOWN
1              BUSINESS
2    SOUTHWEST AIRLINES
3       UNITED AIRLINES
4     AMERICAN AIRLINES
5              MILITARY
6         FEDEX EXPRESS
7       DELTA AIR LINES
8          UPS AIRLINES
9           1US AIRWAYS
Name: Operator, dtype: object

In [33]:
fig = px.scatter(bird_grouped[bird_grouped["Operator"].isin(top10)], 
                 x="Incident Year", 
                 y="Incidents", 
                 color="Operator", 
                 title="Top 10 Airlines with most bird incidents")
fig.show()

In [34]:
# 2.2 Line graph of incidents per airline cumulative
bird_grouped["Cumulative Incidents"] = bird_grouped.groupby(["Operator"])["Incidents"].apply(lambda x: x.cumsum())
filtered_group = bird_grouped[(bird_grouped["Operator"] == "AIR CANADA") | 
                      (bird_grouped["Operator"] == "DELTA AIR LINES") | 
                      (bird_grouped["Operator"] == "AMERICAN AIRLINES") |
                      (bird_grouped["Operator"] == "HAWAIIAN AIR")]
filtered_group.head()

     Incident Year           Operator  Incidents  Cumulative Incidents
2             1990         AIR CANADA          2                     2
14            1990  AMERICAN AIRLINES        453                   453
41            1990    DELTA AIR LINES         52                    52
56            1990       HAWAIIAN AIR         15                    15
111           1991         AIR CANADA          7                     9

In [35]:
fig = px.line(filtered_group, 
              x="Incident Year", 
              y="Cumulative Incidents", 
              color='Operator', 
              title = "Total Bird Incidents per year")
fig.show()

## Exercise 3

1. Create a Choroplet map that shows the total number of incidents per state.
2. Add a slider to change years to your Choropleth map

In [36]:
# 3.1
total_incidents = bird_df.groupby("State")["Record ID"].count().reset_index(name="Total Incidents")
total_incidents.head()

  State  Total Incidents
0    AB               47
1    AK             1010
2    AL             1414
3    AR              837
4    AZ             2455

In [37]:
fig = px.choropleth(total_incidents, 
                    locations="State",  
                    locationmode="USA-states", 
                    color='Total Incidents',      
                    color_continuous_scale="bluyl",
                    range_color=(0, 15000),
                    scope="usa",
                    title= "Total bird incidents per state")
fig.show()

In [38]:
#3.2
state_incidents = bird_df.groupby(["State", "Incident Year"])["Record ID"].count().reset_index(name="Incidents")
state_incidents.head()

  State  Incident Year  Incidents
0    AB           1990          3
1    AB           1991          1
2    AB           1994          1
3    AB           1995          1
4    AB           1996          2

In [39]:
fig = px.choropleth(state_incidents, 
                    locations = "State",  
                    locationmode = "USA-states", 
                    color = "Incidents",      
                    color_continuous_scale = "peach",
                    range_color = (0, state_incidents["Incidents"].max()),
                    scope = "usa",
                    animation_frame = "Incident Year", 
                    title= "Total bird incidents per state and year")
fig.show()

## Exercise 4 (extra credit)

Create a new (fun) additional visualization of a type that we did not cover in class using the same dataset. You can look for inspirations [here](https://plotly.com/python/)! Explain your chart, including choice of dimensions, values, and encodings in comments or a markdown text box.

In [16]:
# Exercise 4: 3D Bird Strike SKYSCRAPER CITY! 🏙️🐦
#
# Real 3D buildings (boxes) where each building represents a combination of
# Flight Phase × Visibility, and the building's HEIGHT shows how many bird
# strikes happened in that combo. The taller the building, the more dangerous!
#
# Dimensions:
#   - X axis: Flight Phase (each phase = a row of buildings)
#   - Y axis: Visibility (Day, Night, Dawn, Dusk)
#   - Z axis (height): Number of incidents
# Color: Aircraft Damage (red glowing = damaged, green = no damage)
#
# It's a futuristic data city you can fly around in! 🌃✨

import pandas as pd
import plotly.graph_objects as go
import numpy as np

# Load and clean
bird_df = pd.read_csv("bird_strikes.csv")
bird_df["Damage Status"] = bird_df["Aircraft Damage"].map({1: "Damaged", 0: "No Damage"})
df = bird_df.dropna(subset=["Flight Phase", "Visibility", "Damage Status"])

grouped = df.groupby(
    ["Flight Phase", "Visibility", "Damage Status"]
)["Record ID"].count().reset_index(name="Incidents")

phases = list(grouped["Flight Phase"].unique())
visibilities = ["DAY", "DUSK", "DAWN", "NIGHT"]
phase_to_x = {p: i * 2 for i, p in enumerate(phases)}  # spaced apart
vis_to_y = {v: i * 2 for i, v in enumerate(visibilities)}

damage_colors = {"Damaged": "#FF3B3B", "No Damage": "#4ECDC4"}

# Helper function: build a box (skyscraper) at position (cx, cy) with given height
def make_building(cx, cy, height, width=0.7, color="#4ECDC4", name="", hover=""):
    # 8 corners of a box
    x = [cx-width, cx+width, cx+width, cx-width, cx-width, cx+width, cx+width, cx-width]
    y = [cy-width, cy-width, cy+width, cy+width, cy-width, cy-width, cy+width, cy+width]
    z = [0, 0, 0, 0, height, height, height, height]

    # 12 triangles to form the 6 faces of the box
    i = [0, 0, 0, 0, 4, 4, 1, 1, 2, 2, 3, 3]
    j = [1, 2, 4, 3, 5, 6, 5, 6, 6, 7, 7, 4]
    k = [2, 3, 5, 4, 6, 7, 6, 2, 7, 3, 4, 0]

    return go.Mesh3d(
        x=x, y=y, z=z,
        i=i, j=j, k=k,
        color=color,
        opacity=0.92,
        flatshading=True,
        name=name,
        hovertext=hover,
        hoverinfo="text",
        showlegend=False,
        lighting=dict(
            ambient=0.4,
            diffuse=0.9,
            specular=0.6,
            roughness=0.3,
            fresnel=0.2
        ),
        lightposition=dict(x=200, y=200, z=400)
    )

# Helper: add glowing "window dots" on the building sides for nighttime city vibes ✨
def make_windows(cx, cy, height, width=0.7):
    if height < 50:
        return None  # too small for windows
    # Random window dots scattered on the front faces
    n_windows = int(min(height / 30, 60))
    np.random.seed(int(cx * 100 + cy * 10))  # consistent windows per building
    window_x, window_y, window_z = [], [], []
    for _ in range(n_windows):
        side = np.random.choice([0, 1, 2, 3])
        h = np.random.uniform(20, height - 10)
        offset = np.random.uniform(-width * 0.7, width * 0.7)
        if side == 0:    # front
            window_x.append(cx + offset); window_y.append(cy - width - 0.01); window_z.append(h)
        elif side == 1:  # back
            window_x.append(cx + offset); window_y.append(cy + width + 0.01); window_z.append(h)
        elif side == 2:  # left
            window_x.append(cx - width - 0.01); window_y.append(cy + offset); window_z.append(h)
        else:            # right
            window_x.append(cx + width + 0.01); window_y.append(cy + offset); window_z.append(h)
    return go.Scatter3d(
        x=window_x, y=window_y, z=window_z,
        mode="markers",
        marker=dict(size=2.5, color="#FFEB3B", opacity=0.9, symbol="square"),
        showlegend=False,
        hoverinfo="skip"
    )

fig = go.Figure()

# Build all the skyscrapers!
for _, row in grouped.iterrows():
    if row["Visibility"] not in vis_to_y:
        continue
    cx = phase_to_x[row["Flight Phase"]]
    cy = vis_to_y[row["Visibility"]]
    height = row["Incidents"]
    color = damage_colors[row["Damage Status"]]

    # Damaged buildings stack on top of no-damage ones (no overlap)
    if row["Damage Status"] == "Damaged":
        cy += 0.85  # offset slightly so damaged sits next to no-damage

    hover = (f"<b>{row['Flight Phase']}</b><br>"
             f"Visibility: {row['Visibility']}<br>"
             f"Status: {row['Damage Status']}<br>"
             f"Incidents: {row['Incidents']:,}")

    fig.add_trace(make_building(cx, cy, height, width=0.4, color=color, hover=hover))

    # Add windows for tall buildings
    windows = make_windows(cx, cy, height, width=0.4)
    if windows:
        fig.add_trace(windows)

# Add a "ground" plane for the city to sit on
ground_x = [-2, max(phase_to_x.values()) + 2, max(phase_to_x.values()) + 2, -2]
ground_y = [-2, -2, max(vis_to_y.values()) + 3, max(vis_to_y.values()) + 3]
ground_z = [0, 0, 0, 0]
fig.add_trace(go.Mesh3d(
    x=ground_x, y=ground_y, z=ground_z,
    i=[0, 0], j=[1, 2], k=[2, 3],
    color="#1a1a2e",
    opacity=0.8,
    showlegend=False,
    hoverinfo="skip",
    lighting=dict(ambient=0.5)
))

# Fake legend entries
for status, color in damage_colors.items():
    label = "💥 Damaged" if status == "Damaged" else "✅ No Damage"
    fig.add_trace(go.Scatter3d(
        x=[None], y=[None], z=[None],
        mode="markers",
        marker=dict(size=14, color=color, symbol="square"),
        name=label,
        showlegend=True
    ))

fig.update_layout(
    title="🏙️ Bird Strike City: A Skyscraper Skyline of Aviation Danger 🐦<br><sub>Building height = # of incidents • 🪟 lit windows = busy buildings • 🖱️ Drag to fly around</sub>",
    width=1000,
    height=780,
    template="plotly_dark",
    scene=dict(
        xaxis=dict(
            title="✈️ Flight Phase",
            tickvals=list(phase_to_x.values()),
            ticktext=list(phase_to_x.keys()),
            gridcolor="rgba(255,255,255,0.05)",
            backgroundcolor="rgb(8, 12, 30)"
        ),
        yaxis=dict(
            title="👁️ Visibility",
            tickvals=list(vis_to_y.values()),
            ticktext=list(vis_to_y.keys()),
            gridcolor="rgba(255,255,255,0.05)",
            backgroundcolor="rgb(8, 12, 30)"
        ),
        zaxis=dict(
            title="📊 # of Incidents",
            gridcolor="rgba(255,255,255,0.05)",
            backgroundcolor="rgb(8, 12, 30)"
        ),
        bgcolor="rgb(3, 5, 18)",
        camera=dict(eye=dict(x=1.8, y=1.8, z=0.7)),
        aspectratio=dict(x=2, y=1.2, z=1.5)
    ),
    margin=dict(t=100, l=0, r=0, b=20),
    legend=dict(bgcolor="rgba(0,0,0,0.6)", bordercolor="white", borderwidth=1, x=0.85, y=0.95),
    updatemenus=[
        dict(
            type="buttons",
            direction="right",
            x=0.5, y=-0.05, xanchor="center",
            buttons=[
                dict(label="🔍 Zoom In",
                     method="relayout",
                     args=[{"scene.camera.eye": dict(x=1.0, y=1.0, z=0.5)}]),
                dict(label="🔭 Zoom Out",
                     method="relayout",
                     args=[{"scene.camera.eye": dict(x=3.0, y=3.0, z=1.5)}]),
                dict(label="🏠 Reset",
                     method="relayout",
                     args=[{"scene.camera.eye": dict(x=1.8, y=1.8, z=0.7)}]),
                dict(label="🚁 Helicopter",
                     method="relayout",
                     args=[{"scene.camera.eye": dict(x=0, y=0, z=2.5)}]),
                dict(label="🚶 Street View",
                     method="relayout",
                     args=[{"scene.camera.eye": dict(x=2.8, y=0.2, z=0.15)}]),
            ]
        )
    ]
)

fig.show()

In [15]:
# Exercise 4: 3D ANIMATED Flapping Bird Strikes! 🐦💫
#
# A 3D scatter plot where every data point is a bird emoji that ACTUALLY
# FLAPS ITS WINGS! We use Plotly animation frames to cycle through different
# bird emojis (wings up → wings down → wings up...) creating a flapping effect.
#
# Press the ▶ Play button to make the whole flock take flight!
#
# Dimensions:
#   - X axis: Speed (knots)
#   - Y axis: Height (altitude)
#   - Z axis: Year
# Color: Flight Phase

import pandas as pd
import plotly.graph_objects as go

# Load and clean
bird_df = pd.read_csv("bird_strikes.csv")
plot_df = bird_df.dropna(
    subset=["Speed", "Height", "Incident Year", "Flight Phase",
            "Operator", "Species Name"]
).copy()
plot_df = plot_df.sample(n=1000, random_state=42)  # smaller for smoother animation

# Two bird poses: wings up vs wings down (the flap cycle!)
# Each phase gets a pair: [wings up, wings down]
bird_flap_pairs = {
    "APPROACH":     ("🦅", "🪶"),
    "TAKEOFF RUN":  ("🐦", "🪺"),
    "LANDING ROLL": ("🦆", "🦢"),
    "CLIMB":        ("🦉", "🌙"),
    "DESCENT":      ("🦜", "🌈"),
    "EN ROUTE":     ("🕊️", "☁️"),
    "LANDING":      ("🐧", "❄️"),
    "TAXI":         ("🦤", "🪶"),
    "DEPARTURE":    ("🐤", "🐣"),
    "LOCAL":        ("🐥", "🪺"),
    "ARRIVAL":      ("🦢", "🪽"),
    "PARKED":       ("🐔", "🥚"),
}

colors = ["#FF6B6B", "#4ECDC4", "#FFD93D", "#95E1D3", "#C06EFA",
          "#FF9F1C", "#A8E6CF", "#FF8B94", "#FFAAA5", "#B5EAD7",
          "#C7CEEA", "#FFDAC1"]

# Helper: build the traces (one per flight phase) for a given wing position
def build_traces(wing_position):  # 0 = wings up, 1 = wings down
    traces = []
    for i, (phase, emoji_pair) in enumerate(bird_flap_pairs.items()):
        phase_data = plot_df[plot_df["Flight Phase"] == phase]
        if len(phase_data) == 0:
            continue
        emoji = emoji_pair[wing_position]
        traces.append(go.Scatter3d(
            x=phase_data["Speed"],
            y=phase_data["Height"],
            z=phase_data["Incident Year"],
            mode="text",
            text=[emoji] * len(phase_data),
            textfont=dict(size=20, color=colors[i % len(colors)]),
            name=f"{emoji_pair[0]} {phase}",
            hovertext=[
                f"<b>{phase}</b><br>"
                f"Airline: {op}<br>"
                f"Species: {sp}<br>"
                f"Speed: {sp_val} kts<br>"
                f"Height: {h} ft<br>"
                f"Year: {yr}"
                for op, sp, sp_val, h, yr in zip(
                    phase_data["Operator"],
                    phase_data["Species Name"],
                    phase_data["Speed"],
                    phase_data["Height"],
                    phase_data["Incident Year"]
                )
            ],
            hoverinfo="text"
        ))
    return traces

# Build the figure with initial frame (wings up)
fig = go.Figure(
    data=build_traces(0),
    frames=[
        go.Frame(data=build_traces(0), name="up"),
        go.Frame(data=build_traces(1), name="down"),
    ]
)

# Add play/pause buttons + flap controls
fig.update_layout(
    title="🐦 FLAPPING Flock of Bird Strikes ✨<br><sub>Press ▶ Play to make them flap! • 🖱️ Drag to rotate • Scroll to zoom</sub>",
    width=950,
    height=750,
    template="plotly_dark",
    scene=dict(
        xaxis_title="✈️ Aircraft Speed (knots)",
        yaxis_title="☁️ Altitude (feet)",
        zaxis_title="📅 Year",
        bgcolor="rgb(15, 20, 50)",
        xaxis=dict(gridcolor="rgba(255,255,255,0.1)"),
        yaxis=dict(gridcolor="rgba(255,255,255,0.1)"),
        zaxis=dict(gridcolor="rgba(255,255,255,0.1)"),
        camera=dict(eye=dict(x=1.2, y=1.2, z=0.8))
    ),
    margin=dict(t=100, l=0, r=0, b=80),
    legend=dict(
        bgcolor="rgba(0,0,0,0.5)",
        bordercolor="white",
        borderwidth=1
    ),
    updatemenus=[
        # Flap controls 🪽
        dict(
            type="buttons",
            direction="right",
            x=0.5,
            y=-0.05,
            xanchor="center",
            showactive=False,
            buttons=[
                dict(
                    label="▶ FLAP!",
                    method="animate",
                    args=[None, {
                        "frame": {"duration": 250, "redraw": True},
                        "fromcurrent": True,
                        "mode": "immediate",
                        "transition": {"duration": 0}
                    }]
                ),
                dict(
                    label="⏸ Land",
                    method="animate",
                    args=[[None], {
                        "frame": {"duration": 0, "redraw": False},
                        "mode": "immediate",
                        "transition": {"duration": 0}
                    }]
                ),
            ]
        ),
    ]
)

fig.show()